// <auto-generated />
namespace NidTid.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MeterPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MeterPost));
        
        string IMigrationMetadata.Id
        {
            get { return "201309301405554_MeterPost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
