// <auto-generated />
namespace NidTid.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SkanskaAB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SkanskaAB));
        
        string IMigrationMetadata.Id
        {
            get { return "201308121359233_Skanska AB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
