// <auto-generated />
namespace NidTid.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class userUpdate3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userUpdate3));
        
        string IMigrationMetadata.Id
        {
            get { return "201309091248257_userUpdate3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
