// <auto-generated />
namespace NidTid.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Reports : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Reports));
        
        string IMigrationMetadata.Id
        {
            get { return "201308151329558_Reports"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
